### ISSUE TITLE
Seems like it gets stuck on GPUpdate /force

### ISSUE THREAD

**Issue by igitthatalot** [Tulpep/Reset-IPv6#4]
Hey there, 

I was wondering if you could do a release without the GPUpdate /force part of it.

I tried extracting your cab, editing RS_resetIPv6.ps1 and commenting out lines 77 and 78. When i try and run resetipv6.diagpkg after that it errors out. I tried removing those lines, removing the /force attribute, etc and it all just fails.

The computer never restarts and it is hung for hours with the above message.

let me know if you have a fix or workaround, thanks. I think this is exactly what I need to solve a problem where the interface is disappearing. 

I think maybe it has to do with the fact that when you run gpupdate /force it prompts you for a question (Y,N) which is why the script might be failing. Let me know.

**Comment by ricardopolo** [comment]
@igitthatalot can you please test running `gpupdate /force /wait:0` and telling if it does work and update the policies without prompt?

**Comment by igitthatalot** [comment]
yes the command 'gpupdate /force /wait:0' does not prompt, you are correct.

**Comment by ricardopolo** [comment]
@igitthatalot but it still updates the policies?

In the next minutes i'll release a new version with this change

**Comment by ricardopolo** [comment]
@igitthatalot we have released a new version. Please download it and tell us if it works.

**Comment by igitthatalot** [comment]
downloading from this link
https://github.com/Tulpep/Reset-IPv6/releases/download/V2.0/ResetIPv6.diagcab

gives me the same file i had before. I tried just downloading your RS_ResetIPv6.ps1 file and adding it, but its the same problem as when i tried to make my own modifications to the file. the ResetIPv6.diagpkg errors out.

am i missing something or the download link hasnt been updated?? thanks for the quick response anyways.

**Comment by ricardopolo** [comment]
Sorry, the correct link is https://github.com/Tulpep/Reset-IPv6/releases/download/2.0.13/ResetIPv6.diagcab

**Comment by ricardopolo** [comment]
@igitthatalot please confirm this new release fixes the issue.

**Comment by igitthatalot** [comment]
Yes it does. the machine does not restart however.

The script did not fix my particular issue however at least it no longer hangs! thanks for the quick response.

**Comment by ricardopolo** [comment]
@igitthatalot great. Maybe post  your particular issue in StackOverflow or ServerFault and share us the like for see if we could change this package to help you.
